# originating https://github.com/TheNetAdmin/Makefile-Templates
# tool marcros
CC := cl
CCFLAG := /std:c++latest /EHsc /Zi
DBGFLAG := -g
CCOBJFLAG := $(CCFLAG) -c

# path marcros
BIN_PATH := bin
SRC_PATH := src
TMP_PATH := temp
SRCLIST	:= $(wildcard $(SRC_PATH)/*.cpp)
EXELIST := $(patsubst $(SRC_PATH)/%.cpp,$(BIN_PATH)/%.exe,$(SRCLIST))

# compile marcros 
TARGET : $(BIN_PATH) $(TMP_PATH) $(EXELIST)

# src files & obj files
SRC := $(foreach x, $(SRC_PATH), $(wildcard $(addprefix $(x)/*,.c*)))
OBJ := $(addprefix $(OBJ_PATH)/, $(addsuffix .obj, $(notdir $(basename $(SRC)))))
OBJ_DEBUG := $(addprefix $(DBG_PATH)/, $(addsuffix .o, $(notdir $(basename $(SRC)))))

# clean files list
DISTCLEAN_LIST := $(patsubst $(SRC_PATH)/%.cpp,$(TMP_PATH)/%.pdb,$(SRCLIST)) \
				  $(patsubst $(SRC_PATH)/%.cpp,$(TMP_PATH)/%.ilk,$(SRCLIST))
				  
CLEAN_LIST := $(EXELIST) \
			  $(DISTCLEAN_LIST)

# default rule
default: all

# non-phony targets
$(TMP_PATH):
	@mkdir $(TMP_PATH)
	
$(BIN_PATH)/%.exe: $(SRC_PATH)/%.cpp
	$(CC) $(CCFLAG) $? /Fe$@  /Fd$(patsubst $(SRC_PATH)/%.cpp,$(TMP_PATH)/%.pdb,$<) /Fo$(patsubst $(SRC_PATH)/%.cpp,$(TMP_PATH)/%.obj,$<)
	rm $(patsubst $(SRC_PATH)/%.cpp,$(TMP_PATH)/%.obj,$<)
	rm $(patsubst $(SRC_PATH)/%.cpp,$(BIN_PATH)/%.ilk,$<)

# phony rules
.PHONY: all
all: $(TARGET)

.PHONY: clean
clean:
	@echo CLEAN $(CLEAN_LIST)
	@rm -f $(CLEAN_LIST)

.PHONY: distclean
distclean:
	@echo CLEAN $(DISTCLEAN_LIST)
	@rm -f $(DISTCLEAN_LIST)